2                              Degre de A :  $$MODELE
2                              Degre de B :
2                              Degre de C :
3
3
2                              Retard:
-0.5989                                        <---- Polyn.A --
-0.0843           
 0.1937                                          <---- Polyn.B --
 0.0707          
-0.4956                                          <---- Polyn.C --
-0.0954                
qxd
256
10
