2                              Degre de A :  $$MODELE
3                              Degre de B :
2                              Degre de C :
3
3
1                              Retard:
-0.6099                                        <---- Polyn.A --
-0.1006          
 0.0816                                          <---- Polyn.B --
 0.1451           
 0.0606  
-0.5288                                          <---- Polyn.C --
-0.1104
qxd
256
10